class LotofacilError(Exception): ...
class SorteioNaoEncontrado(LotofacilError): ...
class ModeloNaoTreinado(LotofacilError): ...
class BaseDesatualizada(LotofacilError): ...
class EstrategiaInvalida(LotofacilError): ...
