from pathlib import Path

BASE = Path(__file__).resolve().parent.parent.parent.parent

COMMANDS = {
    "coleta": {
        "label": "📥 Coleta de Dados",
        "items": [
            {
                "id": "collect_sync",
                "label": "Atualizar Base",
                "description": "Sincroniza novos sorteios da API e atualiza dados de lua e clima",
                "cmd": ["lotofacil", "dados", "atualizar"],
                "cwd": str(BASE),
                "icon": "🔄",
                "group": "coleta",
            },
            {
                "id": "collect_latest",
                "label": "Buscar Último",
                "description": "Busca apenas o sorteio mais recente da API",
                "cmd": ["lotofacil", "dados", "atualizar", "--escopo", "ultimo"],
                "cwd": str(BASE),
                "icon": "📡",
                "group": "coleta",
            },
            {
                "id": "status",
                "label": "Status do DB",
                "description": "Mostra total de sorteios e último concurso",
                "cmd": ["lotofacil", "dados", "status"],
                "cwd": str(BASE),
                "icon": "📋",
                "group": "coleta",
            },
        ],
    },
    "predicao": {
        "label": "🤖 Predição",
        "items": [
            {
                "id": "ml_train",
                "label": "Treinar Clássicos",
                "description": "Treina Frequency + ML ensemble + LSTM clássico",
                "cmd": ["lotofacil", "modelo", "treinar"],
                "cwd": str(BASE),
                "icon": "🏋️",
                "group": "treinar",
            },
            {
                "id": "lab_train_base",
                "label": "Neural: Padrão",
                "description": "Treina LSTM+Attention com dados base+temp+priors",
                "cmd": ["lotofacil", "lab", "train", "--config", "base+temp+priors"],
                "cwd": str(BASE),
                "icon": "🧠",
                "group": "treinar",
            },
            {
                "id": "lab_train_lua",
                "label": "Neural: + Lua",
                "description": "Treina com dados base + fase da lua",
                "cmd": ["lotofacil", "lab", "train", "--config", "base+temp+priors+lua"],
                "cwd": str(BASE),
                "icon": "🌙",
                "group": "treinar",
            },
            {
                "id": "lab_train_lua_clima",
                "label": "Neural: + Lua+Clima",
                "description": "Treina com dados base + lua + clima",
                "cmd": ["lotofacil", "lab", "train", "--config", "base+temp+priors+lua+clima"],
                "cwd": str(BASE),
                "icon": "🌤️",
                "group": "treinar",
            },
            {
                "id": "ml_backtest",
                "label": "Backtest",
                "description": "Walk-forward backtest dos modelos clássicos",
                "cmd": ["lotofacil", "modelo", "backtest"],
                "cwd": str(BASE),
                "icon": "📈",
                "group": "treinar",
            },
            {
                "id": "predict_all",
                "label": "Ensemble (todas)",
                "description": "Combina statistical + ML + neural clássico",
                "cmd": ["lotofacil", "prever", "--abordagem", "todas"],
                "cwd": str(BASE),
                "icon": "🔮",
                "group": "prever",
            },
            {
                "id": "predict_ml",
                "label": "Prever ML",
                "description": "Ensemble LightGBM/RF clássico",
                "cmd": ["lotofacil", "prever", "--abordagem", "ml"],
                "cwd": str(BASE),
                "icon": "🧠",
                "group": "prever",
            },
            {
                "id": "predict_statistical",
                "label": "Prever Estatístico",
                "description": "Frequência e padrões históricos",
                "cmd": ["lotofacil", "prever", "--abordagem", "statistical"],
                "cwd": str(BASE),
                "icon": "📊",
                "group": "prever",
            },
            {
                "id": "predict_neural",
                "label": "Prever Neural",
                "description": "LSTM clássico",
                "cmd": ["lotofacil", "prever", "--abordagem", "neural"],
                "cwd": str(BASE),
                "icon": "⚡",
                "group": "prever",
            },
            {
                "id": "lab_predict_base",
                "label": "Lab: Padrão",
                "description": "Neural lab (base+temp+priors)",
                "cmd": ["lotofacil", "lab", "predict", "--config", "base+temp+priors"],
                "cwd": str(BASE),
                "icon": "🔬",
                "group": "prever",
            },
            {
                "id": "lab_predict_lua",
                "label": "Lab: + Lua",
                "description": "Neural lab com fase da lua",
                "cmd": ["lotofacil", "lab", "predict", "--config", "base+temp+priors+lua"],
                "cwd": str(BASE),
                "icon": "🌙",
                "group": "prever",
            },
            {
                "id": "lab_predict_lua_clima",
                "label": "Lab: + Lua+Clima",
                "description": "Neural lab com lua e clima",
                "cmd": ["lotofacil", "lab", "predict", "--config", "base+temp+priors+lua+clima"],
                "cwd": str(BASE),
                "icon": "🌤️",
                "group": "prever",
            },
            {
                "id": "lab_predict_exp",
                "label": "Lab: Lua+Clima (exp)",
                "description": "Experimental: só lua e clima sem histórico base",
                "cmd": ["lotofacil", "lab", "predict", "--config", "lua+clima"],
                "cwd": str(BASE),
                "icon": "🧪",
                "group": "prever",
            },
        ],
    },
}
