from pathlib import Path

BASE = Path(__file__).resolve().parent.parent.parent

COMMANDS = {
    "coleta": {
        "label": "📥 Coleta de Dados",
        "items": [
            {
                "id": "collect_sync",
                "label": "Atualizar Base",
                "description": "Sincroniza novos sorteios da API Caixa",
                "cmd": ["python", "src/main.py", "collect", "--sync"],
                "cwd": str(BASE),
                "icon": "🔄",
            },
            {
                "id": "collect_latest",
                "label": "Buscar Último",
                "description": "Busca apenas o sorteio mais recente",
                "cmd": ["python", "src/main.py", "collect", "--latest"],
                "cwd": str(BASE),
                "icon": "📡",
            },
            {
                "id": "process",
                "label": "Processar Dados",
                "description": "Migra JSONs para DB + cria consolidated",
                "cmd": ["python", "src/main.py", "process"],
                "cwd": str(BASE),
                "icon": "⚙️",
            },
            {
                "id": "ml_update",
                "label": "ML: Atualizar Base",
                "description": "Update database via lotofacil-ml",
                "cmd": ["python", "src/lotofacil_ml/main.py", "update", "--all"],
                "cwd": str(BASE),
                "icon": "🗄️",
            },
            {
                "id": "status",
                "label": "Status do DB",
                "description": "Mostra total de sorteios e último concurso",
                "cmd": ["python", "src/main.py", "status"],
                "cwd": str(BASE),
                "icon": "📋",
            },
            {
                "id": "ml_history",
                "label": "ML: Histórico",
                "description": "Histórico de predições do ML",
                "cmd": ["python", "src/lotofacil_ml/main.py", "history"],
                "cwd": str(BASE),
                "icon": "📜",
            },
        ],
    },
    "predicao": {
        "label": "🤖 Predição",
        "items": [
            {
                "id": "predict_all",
                "label": "Prever (todas)",
                "description": "Predição 11 números — todas abordagens",
                "cmd": ["python", "src/main.py", "predict", "--approach", "all"],
                "cwd": str(BASE),
                "icon": "🔮",
            },
            {
                "id": "predict_15",
                "label": "Prever 15",
                "description": "Predição de 15 números calibrados",
                "cmd": ["python", "src/main.py", "predict-15"],
                "cwd": str(BASE),
                "icon": "🎲",
            },
            {
                "id": "predict_portfolio",
                "label": "Gerar Portfolio",
                "description": "Gera portfolio de jogos para o próximo concurso",
                "cmd": ["python", "predict_portfolio.py"],
                "cwd": str(BASE),
                "icon": "📊",
            },
            {
                "id": "ml_suggest",
                "label": "ML Suggest",
                "description": "Sugestão de jogo via ensemble ML",
                "cmd": ["python", "src/lotofacil_ml/main.py", "suggest", "--model", "ensemble"],
                "cwd": str(BASE),
                "icon": "🧠",
            },
        ],
    },
    "treinamento": {
        "label": "🎯 Treinamento",
        "items": [
            {
                "id": "train_neural",
                "label": "Treinar Neural",
                "description": "Treina LSTM + Attention (11 números)",
                "cmd": ["python", "src/main.py", "train-neural"],
                "cwd": str(BASE),
                "icon": "🧬",
            },
            {
                "id": "train_neural_15",
                "label": "Treinar Neural 15",
                "description": "Treina LSTM + Attention (15 números)",
                "cmd": ["python", "src/main.py", "train-neural-15"],
                "cwd": str(BASE),
                "icon": "🧬",
            },
            {
                "id": "ml_train",
                "label": "ML: Treinar Modelos",
                "description": "Treina todos os modelos ML (RF, XGBoost, etc)",
                "cmd": ["python", "src/lotofacil_ml/main.py", "train"],
                "cwd": str(BASE),
                "icon": "🏋️",
            },
            {
                "id": "backtest",
                "label": "Backtest",
                "description": "Walk-forward backtest (todas abordagens)",
                "cmd": ["python", "src/main.py", "backtest", "--approach", "all"],
                "cwd": str(BASE),
                "icon": "📈",
            },
            {
                "id": "ml_backtest",
                "label": "ML: Backtest",
                "description": "Backtest completo com relatório HTML",
                "cmd": ["python", "src/lotofacil_ml/main.py", "backtest"],
                "cwd": str(BASE),
                "icon": "📊",
            },
            {
                "id": "validate_kpis",
                "label": "Validar KPIs",
                "description": "Validação abrangente de KPIs",
                "cmd": ["python", "scripts/validate_kpis.py"],
                "cwd": str(BASE),
                "icon": "✅",
            },
        ],
    },
    "analise": {
        "label": "📊 Análise Estatística",
        "items": [
            {
                "id": "analise_pares_impares",
                "label": "Pares / Ímpares",
                "description": "Distribuição par/ímpar nos sorteios",
                "cmd": ["python", "src/analise/analisar_pares_impares.py"],
                "cwd": str(BASE),
                "icon": "📊",
            },
            {
                "id": "analise_faixas",
                "label": "Faixas",
                "description": "Distribuição por faixas (1-5, 6-10, …)",
                "cmd": ["python", "src/analise/analisar_faixas.py"],
                "cwd": str(BASE),
                "icon": "📊",
            },
            {
                "id": "analise_moldura",
                "label": "Moldura",
                "description": "Análise de números de borda/moldura",
                "cmd": ["python", "src/analise/analisar_moldura.py"],
                "cwd": str(BASE),
                "icon": "📊",
            },
            {
                "id": "analise_repetidos",
                "label": "Repetidos Consec.",
                "description": "Números repetidos entre sorteios consecutivos",
                "cmd": ["python", "src/analise/analisar_repetidos_consecutivos.py"],
                "cwd": str(BASE),
                "icon": "🔁",
            },
            {
                "id": "analise_ciclo",
                "label": "Ciclo de Dezenas",
                "description": "Dezenas ausentes nos últimos 4 sorteios",
                "cmd": ["python", "src/analise/ciclo_dezenas.py"],
                "cwd": str(BASE),
                "icon": "🔄",
            },
            {
                "id": "analise_combinacoes",
                "label": "Combinações Dez.",
                "description": "Números que mais co-ocorrem juntos",
                "cmd": ["python", "src/analise/analisar_combinacoes_dezenas.py"],
                "cwd": str(BASE),
                "icon": "🔗",
            },
            {
                "id": "analise_ranking",
                "label": "Ranking Combinações",
                "description": "Ranking completo de combinações ganhadoras",
                "cmd": ["python", "src/analise/ranking_combinacoes_lotofacil.py"],
                "cwd": str(BASE),
                "icon": "🏆",
            },
            {
                "id": "analise_clima",
                "label": "Clima",
                "description": "Correlação entre clima e números sorteados",
                "cmd": ["python", "src/analise/analisar_clima.py"],
                "cwd": str(BASE),
                "icon": "🌤️",
            },
        ],
    },
    "geracao": {
        "label": "🎲 Geração de Jogos",
        "items": [
            {
                "id": "gerar_jogos",
                "label": "Gerar Jogos Sugeridos",
                "description": "10 jogos sugeridos baseados em critérios estatísticos",
                "cmd": ["python", "src/geracao/gerador_jogos_lotofacil.py"],
                "cwd": str(BASE),
                "icon": "🎰",
            },
            {
                "id": "gerar_carteiras",
                "label": "Gerar Carteiras",
                "description": "5 carteiras estratégicas (A/B/C/D/E)",
                "cmd": ["python", "src/geracao/gerador_carteiras_lotofacil.py"],
                "cwd": str(BASE),
                "icon": "💼",
            },
            {
                "id": "predict_from_11",
                "label": "15 from 11",
                "description": "15 números a partir do modelo 11-números",
                "cmd": ["python", "predict_15_from_11.py"],
                "cwd": str(BASE),
                "icon": "🔢",
            },
        ],
    },
}
