from pathlib import Path
import datetime

BASE = Path(__file__).resolve().parent.parent.parent

COMMANDS = {
    "coleta": {
        "label": "📥 Coleta de Dados",
        "items": [
            {
                "id": "collect_sync",
                "label": "Atualizar Base",
                "description": "Sincroniza novos sorteios da API e atualiza dados de lua e clima",
                "cmd": ["lotofacil", "dados", "atualizar"],
                "cwd": str(BASE),
                "icon": "🔄",
            },
            {
                "id": "collect_latest",
                "label": "Buscar Último",
                "description": "Busca apenas o sorteio mais recente da API",
                "cmd": ["lotofacil", "dados", "atualizar", "--latest"],
                "cwd": str(BASE),
                "icon": "📡",
            },
            {
                "id": "status",
                "label": "Status do DB",
                "description": "Mostra total de sorteios e último concurso",
                "cmd": ["lotofacil", "dados", "status"],
                "cwd": str(BASE),
                "icon": "📋",
            },
        ],
    },
    "predicao": {
        "label": "🤖 Predição",
        "items": [
            {
                "id": "predict_all",
                "label": "Ensemble (todas)",
                "description": "Combina statistical + ML + neural clássico → predicao_ensemble_<concurso>.json",
                "cmd": ["lotofacil", "prever", "--approach", "all"],
                "cwd": str(BASE),
                "icon": "🔮",
            },
            {
                "id": "predict_ml",
                "label": "Prever ML",
                "description": "Ensemble LightGBM/RF clássico → predicao_ml_<concurso>.json",
                "cmd": ["lotofacil", "prever", "--approach", "ml"],
                "cwd": str(BASE),
                "icon": "🧠",
            },
            {
                "id": "predict_statistical",
                "label": "Prever Estatístico",
                "description": "Frequência e padrões históricos → predicao_statistical_<concurso>.json",
                "cmd": ["lotofacil", "prever", "--approach", "statistical"],
                "cwd": str(BASE),
                "icon": "📊",
            },
            {
                "id": "predict_neural",
                "label": "Prever Neural",
                "description": "LSTM clássico → predicao_neural_<concurso>.json",
                "cmd": ["lotofacil", "prever", "--approach", "neural"],
                "cwd": str(BASE),
                "icon": "⚡",
            },
            {
                "id": "lab_predict_base",
                "label": "Lab: Padrão",
                "description": "Neural lab (base+temp+priors) → predicao_lab_base-temp-priors_<concurso>.json",
                "cmd": ["lotofacil", "lab", "predict", "--config", "base+temp+priors"],
                "cwd": str(BASE),
                "icon": "🔬",
            },
            {
                "id": "lab_predict_lua",
                "label": "Lab: + Lua",
                "description": "Neural lab com fase da lua → predicao_lab_base-temp-priors-lua_<concurso>.json",
                "cmd": ["lotofacil", "lab", "predict", "--config", "base+temp+priors+lua"],
                "cwd": str(BASE),
                "icon": "🌙",
            },
            {
                "id": "lab_predict_lua_clima",
                "label": "Lab: + Lua + Clima",
                "description": "Neural lab com lua e clima → predicao_lab_base-temp-priors-lua-clima_<concurso>.json",
                "cmd": ["lotofacil", "lab", "predict", "--config", "base+temp+priors+lua+clima"],
                "cwd": str(BASE),
                "icon": "🌤️",
            },
            {
                "id": "lab_predict_exp",
                "label": "Lab: Lua+Clima (exp)",
                "description": "Experimental: só lua e clima, sem histórico base → predicao_lab_lua-clima_<concurso>.json",
                "cmd": ["lotofacil", "lab", "predict", "--config", "lua+clima"],
                "cwd": str(BASE),
                "icon": "🧪",
            },
        ],
    },
    "treinamento": {
        "label": "🎯 Treinamento",
        "items": [
            {
                "id": "ml_train",
                "label": "Treinar Clássicos",
                "description": "Treina Frequency + ML ensemble + LSTM clássico (lotofacil_ml)",
                "cmd": ["lotofacil", "modelo", "treinar"],
                "cwd": str(BASE),
                "icon": "🏋️",
            },
            {
                "id": "lab_train_base",
                "label": "Neural: Padrão",
                "description": "Treina LSTM+Attention com dados de concurso (base+temp+priors) → neural_base-temp-priors.keras",
                "cmd": ["lotofacil", "lab", "train", "--config", "base+temp+priors"],
                "cwd": str(BASE),
                "icon": "🧠",
            },
            {
                "id": "lab_train_lua",
                "label": "Neural: + Lua",
                "description": "Treina com dados de concurso + fase da lua → neural_base-temp-priors-lua.keras",
                "cmd": ["lotofacil", "lab", "train", "--config", "base+temp+priors+lua"],
                "cwd": str(BASE),
                "icon": "🌙",
            },
            {
                "id": "lab_train_lua_clima",
                "label": "Neural: + Lua + Clima",
                "description": "Treina com dados de concurso + lua + clima → neural_base-temp-priors-lua-clima.keras",
                "cmd": ["lotofacil", "lab", "train", "--config", "base+temp+priors+lua+clima"],
                "cwd": str(BASE),
                "icon": "🌤️",
            },
            {
                "id": "lab_train_exp",
                "label": "Neural: Lua+Clima (exp)",
                "description": "Experimental: treina só com lua e clima, sem histórico base → neural_lua-clima.keras",
                "cmd": ["lotofacil", "lab", "train", "--config", "lua+clima"],
                "cwd": str(BASE),
                "icon": "🧪",
            },
            {
                "id": "ml_backtest",
                "label": "Backtest",
                "description": "Walk-forward backtest dos modelos clássicos → relatório HTML",
                "cmd": ["lotofacil", "modelo", "backtest"],
                "cwd": str(BASE),
                "icon": "📈",
            },
        ],
    },
    "analise": {
        "label": "📊 Análise",
        "items": [
            {
                "id": "analise_historico",
                "label": "Histórico de Predições",
                "description": "Últimas 20 predições registradas",
                "cmd": ["lotofacil", "modelo", "historico"],
                "cwd": str(BASE),
                "icon": "📜",
            },
            {
                "id": "analise_validar",
                "label": "Validar Predições",
                "description": "Confere predições pendentes contra resultados reais",
                "cmd": ["lotofacil", "modelo", "validar"],
                "cwd": str(BASE),
                "icon": "✅",
            },
            {
                "id": "analise_status",
                "label": "Status do Banco",
                "description": "Total de sorteios e concurso mais recente",
                "cmd": ["lotofacil", "dados", "status"],
                "cwd": str(BASE),
                "icon": "📋",
            },
            {
                "id": "analise_backtest",
                "label": "Backtest",
                "description": "Walk-forward backtest → relatório HTML",
                "cmd": ["lotofacil", "modelo", "backtest"],
                "cwd": str(BASE),
                "icon": "📈",
            },
        ],
    },
    "geracao": {
        "label": "🎲 Geração de Jogos",
        "items": [
            {
                "id": "geracao_portfolio",
                "label": "Gerar Portfólio",
                "description": "Portfólio tiered para o próximo concurso",
                "cmd": ["lotofacil", "portfolio"],
                "cwd": str(BASE),
                "icon": "📊",
            },
            {
                "id": "geracao_portfolio_8",
                "label": "Gerar Portfólio (8 jogos)",
                "description": "Portfólio com 8 jogos distribuídos por tier",
                "cmd": ["lotofacil", "portfolio", "--jogos", "8"],
                "cwd": str(BASE),
                "icon": "🎯",
            },
            {
                "id": "geracao_prever",
                "label": "Prever (ensemble)",
                "description": "Predição ensemble — todas as abordagens",
                "cmd": ["lotofacil", "prever"],
                "cwd": str(BASE),
                "icon": "🔮",
            },
        ],
    },
    "lab": {
        "label": "🔬 Experimentos (Lab)",
        "items": [
            {
                "id": "lab_backfill_clima",
                "label": "Backfill Clima",
                "description": "Preenche histórico climático via Open-Meteo",
                "cmd": ["lotofacil", "lab", "backfill-clima"],
                "cwd": str(BASE),
                "icon": "🌤️",
            },
            {
                "id": "lab_lunar_check",
                "label": "Lunar Check (hoje)",
                "description": "Mostra features lunares para a data de hoje",
                "cmd": ["lotofacil", "lab", "lunar-check",
                        "--data", datetime.date.today().isoformat()],
                "cwd": str(BASE),
                "icon": "🌙",
            },
            {
                "id": "lab_ablation",
                "label": "Ablation Study",
                "description": "Compara configs de features (clima, lua, base)",
                "cmd": ["lotofacil", "lab", "ablation", "--n-test", "50"],
                "cwd": str(BASE),
                "icon": "🧪",
            },
        ],
    },
}
