from pathlib import Path

PROJETO_RAIZ = Path(__file__).resolve().parent.parent.parent.parent
DADOS_DIR = PROJETO_RAIZ / "dados"
SAIDA_DIR = PROJETO_RAIZ / "saida"
DB_PATH = DADOS_DIR / "lotofacil.db"
MODELOS_DIR = SAIDA_DIR / "modelos"
JOGOS_DIR = SAIDA_DIR / "jogos"
PREDICOES_DIR = SAIDA_DIR / "predicoes"
RELATORIOS_DIR = SAIDA_DIR / "relatorios"
EXPERIMENTOS_DIR = SAIDA_DIR / "experimentos"

DADOS_DIR.mkdir(parents=True, exist_ok=True)
SAIDA_DIR.mkdir(parents=True, exist_ok=True)
MODELOS_DIR.mkdir(parents=True, exist_ok=True)
JOGOS_DIR.mkdir(parents=True, exist_ok=True)
PREDICOES_DIR.mkdir(parents=True, exist_ok=True)
RELATORIOS_DIR.mkdir(parents=True, exist_ok=True)
EXPERIMENTOS_DIR.mkdir(parents=True, exist_ok=True)

TOTAL_NUMEROS = 25
NUMEROS_POR_SORTEIO = 15
VALID_NUMBERS = set(range(1, TOTAL_NUMEROS + 1))

API_BASE_URL = "https://loteriascaixa-api.herokuapp.com/api"
API_LOTOFACIL = f"{API_BASE_URL}/lotofacil"
API_TIMEOUT = 30
API_RETRIES = 5
API_RETRY_MIN = 1
API_RETRY_MAX = 10
USER_AGENT = "lotofacil-prediction/2.0"

FREQ_WINDOWS = [10, 30, 100]
MIN_HISTORY = 20

RF_N_ESTIMATORS = 200
RF_MAX_DEPTH = 10
RF_MIN_SAMPLES_LEAF = 5
CV_N_SPLITS = 5

LSTM_WINDOW_SIZE = 50
LSTM_UNITS_1 = 128
LSTM_UNITS_2 = 128
LSTM_UNITS_3 = 64
LSTM_DROPOUT = 0.3
LSTM_DROPOUT_INPUT = 0.2
LSTM_DROPOUT_DENSE = 0.4
LSTM_LR = 0.001
LSTM_LR_MIN = 0.00001
LSTM_LR_FACTOR = 0.5
LSTM_LR_PATIENCE = 5
LSTM_EPOCHS = 100
LSTM_BATCH_SIZE = 32
LSTM_PATIENCE = 10
FOCAL_LOSS_GAMMA = 2.0
FOCAL_LOSS_ALPHA = 0.75
NEURAL_VAL_SPLIT = 0.2
ATTENTION_DIM = 128
ATTENTION_HEADS = 4

TRANSFORMER_MODEL_DIM = 64
TRANSFORMER_HEADS = 4
TRANSFORMER_KEY_DIM = 16
TRANSFORMER_BLOCKS = 2
TRANSFORMER_DROPOUT = 0.3
TRANSFORMER_EPOCHS = 100
TRANSFORMER_BATCH_SIZE = 32
TRANSFORMER_PATIENCE = 10
AE_ENCODER_DIMS = [64, 32, 16]
AE_BOTTLENECK_DIM = 8
AE_DROPOUT = 0.2
AE_EPOCHS = 100
AE_BATCH_SIZE = 32
AE_PATIENCE = 10

BACKTEST_TRAIN_WINDOW = 300
BACKTEST_RETRAIN_EVERY = 50
BACKTEST_MIN_TRAIN = 100
VALIDATION_N_BACKTEST = 100

RANDOM_SEED = 42

ENSEMBLE_WEIGHTS = {
    "frequency": 0.20,
    "ml": 0.45,
    "lstm": 0.35,
}

FAIXAS_ACERTOS = [11, 12, 13, 14, 15]
CUSTO_POR_JOGO = 3.50
TABELA_PREMIOS: dict[int, float] = {
    11: 7.00,
    12: 14.00,
    13: 35.00,
    14: 2_000.00,
    15: 1_500_000.00,
}

SCHEDULE_UPDATE_DAYS = ["mon", "wed", "fri"]
SCHEDULE_UPDATE_HOUR = 23
SCHEDULE_RETRAIN_DAY = "mon"
SCHEDULE_RETRAIN_HOUR = 2

TOTAL_NUMBERS = TOTAL_NUMEROS
NUMBERS_PER_DRAW = NUMEROS_POR_SORTEIO
MODELS_DIR = MODELOS_DIR
DATA_DIR = DADOS_DIR
OUTPUT_DIR = SAIDA_DIR
DB_PATH_OLD = DADOS_DIR / "lotofacil.db"
COST_PER_GAME = CUSTO_POR_JOGO
PRIZE_TABLE = TABELA_PREMIOS
HIT_THRESHOLDS = FAIXAS_ACERTOS
OUTPUT_PREDICTIONS = PREDICOES_DIR
OUTPUT_REPORTS = RELATORIOS_DIR
OUTPUT_MODELS = MODELOS_DIR
SRC_DIR = PROJETO_RAIZ / "src"
PROJECT_ROOT = PROJETO_RAIZ
BACKTEST_DEFAULT_N = VALIDATION_N_BACKTEST
